uploads = []
outputs = []

[[generated]]
id = "SK0PBpXSgANBDP4JKJTNb"
uri = "file://artifacts/combo-finder/assets/images/icon.png"
type = "image"
title = "combo-finder app icon"

[[generated]]
id = "n9j62o1O-KQyIrAXfgasn"
uri = "file://artifacts/combo-finder/assets/images/splash-icon.png"
type = "image"
title = "combo-finder splash icon"
