kind = "mobile"
previewPath = "/mobile/"
title = "ComboFinder Mobile"
version = "1.0.0"
id = "artifacts/combo-finder"
router = "expo-domain"

[[services]]
name = "expo"
ensurePreviewReachable = "/status"
paths = [ "/mobile/" ]
localPort = 20397

[services.development]
run = "pnpm --filter @workspace/combo-finder run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/combo-finder", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/combo-finder", "run", "serve" ]

[services.env]
PORT = "20397"
BASE_PATH = "/mobile/"
